// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOOyIvyOGX9ThRboY8QzMwDHKX9uVs4F8',
    appId: '1:530814919987:web:3e3dde00f3ed15906bca46',
    messagingSenderId: '530814919987',
    projectId: 'smart-clinic-for-psychiatry',
    authDomain: 'smart-clinic-for-psychiatry.firebaseapp.com',
    databaseURL: 'https://smart-clinic-for-psychiatry-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clinic-for-psychiatry.appspot.com',
    measurementId: 'G-ZZVNT67PTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRDDFDfdxqPe3pIXQlnRanCfPdAT4fULo',
    appId: '1:530814919987:android:778f005d5b5d733d6bca46',
    messagingSenderId: '530814919987',
    projectId: 'smart-clinic-for-psychiatry',
    databaseURL: 'https://smart-clinic-for-psychiatry-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clinic-for-psychiatry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMyeBuQ__2vssm2tcE-mtxT9jl6HFO-E',
    appId: '1:530814919987:ios:138baf50095fd47d6bca46',
    messagingSenderId: '530814919987',
    projectId: 'smart-clinic-for-psychiatry',
    databaseURL: 'https://smart-clinic-for-psychiatry-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clinic-for-psychiatry.appspot.com',
    iosBundleId: 'com.example.smartClinicForPsychiatry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMyeBuQ__2vssm2tcE-mtxT9jl6HFO-E',
    appId: '1:530814919987:ios:3011a13b0a5e18d96bca46',
    messagingSenderId: '530814919987',
    projectId: 'smart-clinic-for-psychiatry',
    databaseURL: 'https://smart-clinic-for-psychiatry-default-rtdb.firebaseio.com',
    storageBucket: 'smart-clinic-for-psychiatry.appspot.com',
    iosBundleId: 'com.example.smartClinicForPsychiatry.RunnerTests',
  );
}
